// Brand Approvals Data — sourced from #the-vault-brand-approvals
// Last updated: 2026-05-19
// To update: replace entries in SUBMISSIONS and re-deploy

window.APPROVALS_DATA = {
  lastUpdated: "2026-05-19",
  channelName: "#the-vault-brand-approvals",
  retentionNote: "Messages before Feb 18 2026 partially deleted by Slack retention policy. Jan–Feb totals are lower-bound estimates.",

  submissions: [
    // ── MAY 2026 ──
    { date: "2026-05-18", brand: "ACT Fiber",      submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-18", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-18", brand: "OPPO",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-18", brand: "Walmart Mexico",  submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-18", brand: "Vodafone",        submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-15", brand: "OPPO",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-14", brand: "Roku",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-14", brand: "Burger King",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-14", brand: "Google",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-14", brand: "Google",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-14", brand: "ACT Fiber",       submitter: "Gail Hilton", urgent: true  },
    { date: "2026-05-13", brand: "Fareast",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-13", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-13", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-13", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-13", brand: "ACT Fiber",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-12", brand: "Burger King",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-11", brand: "ACT Fiber",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-11", brand: "ACT Fiber",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-11", brand: "Xiaomi",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-11", brand: "Microsoft",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-08", brand: "ACT Fiber",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-08", brand: "ACT Fiber",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-08", brand: "ACT Fiber",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-08", brand: "Samsung",         submitter: "Gail Hilton", urgent: true  },
    { date: "2026-05-07", brand: "Disney",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-07", brand: "Comcast/Xumo",    submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-07", brand: "Comcast/Xumo",    submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-07", brand: "ACT Fiber",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-06", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-06", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-06", brand: "SNCF",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-06", brand: "Le Monde",        submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-06", brand: "Walmart/Sams Club", submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-06", brand: "ACT Fiber",       submitter: "Gail Hilton", urgent: true  },
    { date: "2026-05-06", brand: "Microsoft",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-05", brand: "Media Expert",    submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-05", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-05", brand: "ACT Fiber",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-04", brand: "Adidas",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-04", brand: "OVO",             submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-04", brand: "Moonton",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-04", brand: "Le Monde",        submitter: "Gail Hilton", urgent: true  },
    { date: "2026-05-04", brand: "Opera",           submitter: "Gail Hilton", urgent: false },
    { date: "2026-05-04", brand: "ACT Fiber",       submitter: "Gail Hilton", urgent: false },
    // ── APRIL 2026 ──
    { date: "2026-04-30", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-30", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-30", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-30", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-30", brand: "iFood",           submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-30", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-30", brand: "Vodafone India",  submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-30", brand: "ACT Fiber",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-30", brand: "ACT Fiber",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-30", brand: "ACT Fiber",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-29", brand: "Microsoft",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-29", brand: "Media Expert",    submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-29", brand: "Xiaomi",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-28", brand: "Le Monde",        submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-28", brand: "ACT Fiber",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-28", brand: "SNCF",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-28", brand: "Moonton",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-27", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-27", brand: "OVO",             submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-27", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-27", brand: "ACT Fiber",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-27", brand: "Vodafone India",  submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-27", brand: "Zain",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-27", brand: "Vodafone India",  submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-24", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-24", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-24", brand: "iFood",           submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-24", brand: "SNCF",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-24", brand: "SNCF",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-24", brand: "Burger King",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-24", brand: "Burger King",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-24", brand: "OPPO",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-23", brand: "ACT Fiber",       submitter: "Gail Hilton", urgent: true  },
    { date: "2026-04-23", brand: "Vodafone India",  submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-22", brand: "Burger King",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-22", brand: "Amazon",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-22", brand: "Xiaomi",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-22", brand: "Xiaomi",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-21", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-21", brand: "SNCF",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-21", brand: "Ford",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-21", brand: "Hyundai",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-21", brand: "IKEA",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-21", brand: "Le Monde",        submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-20", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-20", brand: "Disney",          submitter: "Gail Hilton", urgent: true  },
    { date: "2026-04-20", brand: "PlayStudios",     submitter: "Gail Hilton", urgent: true  },
    { date: "2026-04-20", brand: "IKEA",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-20", brand: "IKEA",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-20", brand: "IKEA",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-20", brand: "Sony",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-20", brand: "Sony",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-17", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-17", brand: "IKEA",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-17", brand: "IKEA",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-17", brand: "Disney",          submitter: "Gail Hilton", urgent: true  },
    { date: "2026-04-17", brand: "Burger King",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-17", brand: "Xiaomi",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-16", brand: "PlayStudios",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-16", brand: "ACT Fiber",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-15", brand: "Disney",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-15", brand: "SNCF",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-15", brand: "Burger King",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-15", brand: "Xiaomi",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-14", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-14", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-14", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-14", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-14", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-14", brand: "Burger King",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-14", brand: "Telkomsel",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-14", brand: "Alpha Theta",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-14", brand: "Alpha Theta",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-14", brand: "Le Monde",        submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-13", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-13", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-13", brand: "H&M",             submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-13", brand: "Le Monde",        submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-13", brand: "Xiaomi",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-10", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-10", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-10", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-10", brand: "Google",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-10", brand: "Inpost",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-09", brand: "Burger King",     submitter: "Gail Hilton", urgent: true  },
    { date: "2026-04-09", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-09", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-09", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-09", brand: "Telkomsel",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-09", brand: "Weather Channel", submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-08", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-08", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-08", brand: "Burger King",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-08", brand: "Le Monde",        submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-08", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-08", brand: "Lexus",           submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-08", brand: "Garmin",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-07", brand: "H&M",             submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-07", brand: "Inpost",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-07", brand: "Xiaomi",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-06", brand: "Meta",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-06", brand: "Comcast",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-06", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-06", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-03", brand: "Weather Channel", submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-02", brand: "OnePlus",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-02", brand: "Le Monde",        submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-02", brand: "Burger King",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-02", brand: "Burger King",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-01", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-01", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-01", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-01", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-01", brand: "Comcast",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-01", brand: "Meta",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-04-01", brand: "Touch 'n Go",     submitter: "Gail Hilton", urgent: false },
    // ── MARCH 2026 ──
    { date: "2026-03-31", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-31", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-31", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-31", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-31", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-31", brand: "Xiaomi",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-31", brand: "Touch 'n Go",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-31", brand: "Vodacom",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-31", brand: "Le Monde",        submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-31", brand: "Le Monde",        submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-31", brand: "Disney",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-27", brand: "Burger King",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-26", brand: "Vodacom",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-26", brand: "Xiaomi",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-26", brand: "Xiaomi",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-25", brand: "Le Monde",        submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-25", brand: "Burger King",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-25", brand: "Inpost",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-25", brand: "Opera",           submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-24", brand: "Burger King",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-24", brand: "SNCF",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-24", brand: "SNCF",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-24", brand: "Le Monde",        submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-24", brand: "Xiaomi",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-23", brand: "Disney",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-23", brand: "Le Monde",        submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-23", brand: "Xiaomi",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-20", brand: "Burger King",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-20", brand: "SNCF",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-19", brand: "Burger King",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-19", brand: "Le Monde",        submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-18", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-18", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-17", brand: "Telkomsel",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-16", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-13", brand: "Momo",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-12", brand: "TrueMoney",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-12", brand: "Naver",           submitter: "Gail Hilton", urgent: true  },
    { date: "2026-03-11", brand: "Inpost",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-11", brand: "Sony",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-11", brand: "Roku",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-11", brand: "Serato",          submitter: "Gail Hilton", urgent: true  },
    { date: "2026-03-10", brand: "Tinder",          submitter: "Gail Hilton", urgent: true  },
    { date: "2026-03-09", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-09", brand: "Microsoft",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-09", brand: "Disney",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-09", brand: "Roku",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-09", brand: "Algoriddim",      submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-09", brand: "Honda",           submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-06", brand: "Walmart Mexico",  submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-06", brand: "Inpost",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-05", brand: "Microsoft",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-05", brand: "Telkomsel",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-05", brand: "Le Monde",        submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-05", brand: "Sony",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-05", brand: "Serato",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-04", brand: "Le Monde",        submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-03", brand: "Microsoft",       submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-02", brand: "Meta",            submitter: "Gail Hilton", urgent: false },
    { date: "2026-03-02", brand: "Sony",            submitter: "Gail Hilton", urgent: false },
    // ── FEBRUARY 2026 (partial) ──
    { date: "2026-02-27", brand: "Disney",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-02-27", brand: "Foody/Delivery Hero", submitter: "Gail Hilton", urgent: false },
    { date: "2026-02-27", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-02-26", brand: "Serato",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-02-26", brand: "Disney",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-02-26", brand: "Disney",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-02-25", brand: "Opera",           submitter: "Gail Hilton", urgent: false },
    { date: "2026-02-25", brand: "GM/Chevy",        submitter: "Gail Hilton", urgent: false },
    { date: "2026-02-25", brand: "Xiaomi",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-02-24", brand: "Xiaomi",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-02-23", brand: "Le Monde",        submitter: "Gail Hilton", urgent: false },
    { date: "2026-02-23", brand: "Disney",          submitter: "Gail Hilton", urgent: false },
    { date: "2026-02-19", brand: "StudySmarter",    submitter: "Gail Hilton", urgent: false },
    { date: "2026-02-18", brand: "Le Monde",        submitter: "Gail Hilton", urgent: false },
    // ── JANUARY 2026 (partial) ──
    { date: "2026-01-05", brand: "Disney/Hulu",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-01-05", brand: "Disney/Hulu",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-01-05", brand: "Disney/Hulu",     submitter: "Gail Hilton", urgent: false },
    { date: "2026-01-05", brand: "Samsung",         submitter: "Gail Hilton", urgent: false },
    { date: "2026-01-05", brand: "Trendyol",        submitter: "Gail Hilton", urgent: false },
    { date: "2026-01-05", brand: "Delivery Hero",   submitter: "Gail Hilton", urgent: false },
  ],

  milestones: [
    { date: "2026-01-05", text: "Channel relaunches — Gail joins, first submissions posted" },
    { date: "2026-03-11", text: "Serato flagged urgent — launching same day" },
    { date: "2026-04-20", text: "Earth Day fast-track: Disney + PlayStudios expedited" },
    { date: "2026-05-08", text: "Samsung & Walmart flagged as pressing, @here escalation" },
    { date: "2026-05-14", text: "ACT Fiber near launch deadline — 3 @here escalations" },
    { date: "2026-05-14", text: "\"We are all caught up!!!\" — backlog fully cleared" },
  ]
};
